services:
  - type: web
    name: powerbi-platform
    env: python
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: gunicorn powerbi_platform.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: powerbi_platform.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: powerbi-db
          property: connectionString

databases:
  - name: powerbi-db
    databaseName: powerbi
    user: powerbi_user
